name: "📅 Generate Monthly Schedule"

on:
  schedule:
    # At 06:00 UTC on day-of-month 25
    - cron: '0 6 25 * *'
  workflow_dispatch: {}

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      # 1) checkout code
      - uses: actions/checkout@v3

      # 2) set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 3) install dependencies from requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4) compute next month/year
      - name: Compute next-month year & month
        id: vars
        run: |
          python - << 'EOF'
import datetime, os
today = datetime.date.today()
first = today.replace(day=1)
# jump to next month
nm = first + datetime.timedelta(days=32)
y, m = nm.year, nm.month
# export for GH Actions
with open(os.environ['GITHUB_OUTPUT'], 'a') as fh:
    fh.write(f"month={m}\n")
    fh.write(f"year={y}\n")
EOF

      # 5) run the scheduler
      - name: Generate schedule
        run: |
          python scheduler.py \
            --input availability.xlsx \
            --month ${{ steps.vars.outputs.month }} \
            --year  ${{ steps.vars.outputs.year }} \
            --output schedule_${{ steps.vars.outputs.month }}_${{ steps.vars.outputs.year }}.xlsx

      # 6) commit & push any changes
      - name: Commit & push schedule
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add schedule_*.xlsx
          git diff --quiet || git commit -m "📅 Monthly schedule for ${{ steps.vars.outputs.month }}/${{ steps.vars.outputs.year }}"
          git push
